location = /api/train-bingo {
  add_header Content-Security-Policy "upgrade-insecure-requests" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  include fastcgi_params;
  fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
  fastcgi_param SCRIPT_FILENAME /var/www/OpenBanners/server/train-bingo.php;
  fastcgi_param SCRIPT_NAME /train-bingo.php;
}

location / {
  add_header Content-Security-Policy "upgrade-insecure-requests" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  proxy_pass http://127.0.0.1:18080;
  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto https;
  proxy_set_header X-Forwarded-Port 443;
  proxy_set_header Forwarded "proto=https;host=$host";
}
