const flags = {
  "United States": "🇺🇸",
  Japan: "🇯🇵",
  Germany: "🇩🇪",
  Spain: "🇪🇸",
  "United Kingdom": "🇬🇧",
  Brazil: "🇧🇷",
  China: "🇨🇳",
  France: "🇫🇷",
  Netherlands: "🇳🇱",
  Russia: "🇷🇺",
  Italy: "🇮🇹",
  Peru: "🇵🇪",
  Poland: "🇵🇱",
  Indonesia: "🇮🇩",
  Chile: "🇨🇱",
  Belgium: "🇧🇪",
  Australia: "🇦🇺",
  Taiwan: "🇹🇼",
  Sweden: "🇸🇪",
  Finland: "🇫🇮",
  Portugal: "🇵🇹",
  "South Korea": "🇰🇷",
  Ukraine: "🇺🇦",
  Canada: "🇨🇦",
  Philippines: "🇵🇭",
  Czechia: "🇨🇿",
  Switzerland: "🇨🇭",
  Norway: "🇳🇴",
  Austria: "🇦🇹",
  India: "🇮🇳",
  Mexico: "🇲🇽",
  Argentina: "🇦🇷",
  Denmark: "🇩🇰",
  Malaysia: "🇲🇾",
  Hungary: "🇭🇺",
  Ecuador: "🇪🇨",
  Lithuania: "🇱🇹",
  Colombia: "🇨🇴",
  "New Zealand": "🇳🇿",
  "South Africa": "🇿🇦",
  Estonia: "🇪🇪",
  "Hong Kong": "🇭🇰",
  Belarus: "🇧🇾",
  Bolivia: "🇧🇴",
  Thailand: "🇹🇭",
  Greece: "🇬🇷",
  Singapore: "🇸🇬",
  "Sri Lanka": "🇱🇰",
  Turkey: "🇹🇷",
  Slovakia: "🇸🇰",
  Romania: "🇷🇴",
  Croatia: "🇭🇷",
  Latvia: "🇱🇻",
  Ireland: "🇮🇪",
  "El Salvador": "🇸🇻",
  Honduras: "🇭🇳",
  Bulgaria: "🇧🇬",
  Uruguay: "🇺🇾",
  Paraguay: "🇵🇾",
  Slovenia: "🇸🇮",
  "United Arab Emirates": "🇦🇪",
  Kazakhstan: "🇰🇿",
  Maldives: "🇲🇻",
  Panama: "🇵🇦",
  Bangladesh: "🇧🇩",
  Macao: "🇲🇴",
  "Dominican Republic": "🇩🇴",
  Serbia: "🇷🇸",
  Vietnam: "🇻🇳",
  "Costa Rica": "🇨🇷",
  Israel: "🇮🇱",
  Venezuela: "🇻🇪",
  Luxembourg: "🇱🇺",
  Guatemala: "🇬🇹",
  Iceland: "🇮🇸",
  Gibraltar: "🇬🇮",
  Georgia: "🇬🇪",
  Uzbekistan: "🇺🇿",
  Andorra: "🇦🇩",
  "North Macedonia": "🇲🇰",
  Cyprus: "🇨🇾",
  Moldova: "🇲🇩",
  "Myanmar (Burma)": "🇲🇲",
  Morocco: "🇲🇦",
  Qatar: "🇶🇦",
  Egypt: "🇪🇬",
  "French Polynesia": "🇵🇫",
  Armenia: "🇦🇲",
  Lebanon: "🇱🇧",
  "New Caledonia": "🇳🇨",
  Malta: "🇲🇹",
  Nicaragua: "🇳🇮",
  "Bosnia and Herzegovina": "🇧🇦",
  Réunion: "🇷🇪",
  Kenya: "🇰🇪",
  "Puerto Rico": "🇵🇷",
  Cambodia: "🇰🇭",
  Montenegro: "🇲🇪",
  Jersey: "🇯🇪",
  Mauritius: "🇲🇺",
  Nepal: "🇳🇵",
  Tunisia: "🇹🇳",
  Greenland: "🇬🇱",
  Guadeloupe: "🇬🇵",
  Fiji: "🇫🇯",
  Aruba: "🇦🇼",
  "Cayman Islands": "🇰🇾",
  "North Korea": "🇰🇵",
  Curaçao: "🇨🇼",
  Azerbaijan: "🇦🇿",
  "Trinidad and Tobago": "🇹🇹",
  Brunei: "🇧🇳",
  Seychelles: "🇸🇨",
  Kuwait: "🇰🇼",
  Albania: "🇦🇱",
  Rwanda: "🇷🇼",
  "The Bahamas": "🇧🇸",
  "Åland Islands": "🇦🇽",
  "Faroe Islands": "🇫🇴",
  Barbados: "🇧🇧",
  Suriname: "🇸🇷",
  Jamaica: "🇯🇲",
  Martinique: "🇲🇶",
  Zambia: "🇿🇲",
  Monaco: "🇲🇨",
  Bahrain: "🇧🇭",
  "Saudi Arabia": "🇸🇦",
  Antarctica: "🇦🇶",
  Namibia: "🇳🇦",
  Cuba: "🇨🇺",
  Mayotte: "🇾🇹",
  "Svalbard and Jan Mayen": "🇸🇯",
  Mongolia: "🇲🇳",
  Kyrgyzstan: "🇰🇬",
  "Cook Islands": "🇨🇰",
  Jordan: "🇯🇴",
  "U.S. Virgin Islands": "🇻🇮",
  "St Lucia": "🇱🇨",
  "Northern Mariana Islands": "🇲🇵",
  "San Marino": "🇸🇲",
  Laos: "🇱🇦",
  Sudan: "🇸🇩",
  Oman: "🇴🇲",
  Nauru: "🇳🇷",
  Guernsey: "🇬🇬",
  "Isle of Man": "🇮🇲",
  Guam: "🇬🇺",
  Benin: "🇧🇯",
  Zimbabwe: "🇿🇼",
  Botswana: "🇧🇼",
};

export default flags;
