import { describe, expect, test, vi } from "vitest";
import { parseUmmMissionSet } from "./umm";
import {
  buildRouteHistoryEntry,
  buildUmmMissionSet,
  compactRouteSnapshot,
  generateReroute,
  inflateStoredRoute,
  restoreDraftFromHistoryEntry,
} from "./routeGenerator";

function buildTestDraft() {
  const missionSet = {
    fileFormatVersion: 1,
    missionSetName: "Route Generator Banner",
    missionSetDescription: "Generated by a unit test.",
    plannedBannerLength: 6,
    missions: Array.from({ length: 6 }, (_missionValue, missionIndex) => ({
      missionTitle: `Imported Mission ${missionIndex + 1}`,
      portals: Array.from({ length: 7 }, (_portalValue, portalIndex) => {
        const absoluteIndex = missionIndex * 7 + portalIndex;

        return {
          guid: `route-generator-guid-${absoluteIndex + 1}`,
          title: `Portal ${absoluteIndex + 1}`,
          location: {
            latitude: 52.1 + absoluteIndex * 0.0011,
            longitude: 6.8 + absoluteIndex * 0.0012,
          },
          isStartPoint: absoluteIndex === 0,
        };
      }),
    })),
  };
  const importedDraft = parseUmmMissionSet(
    JSON.stringify(missionSet),
    "route-generator.umm.json"
  );

  return {
    id: "draft-1",
    createdAt: 1,
    updatedAt: 1,
    source: importedDraft.source,
    metadata: importedDraft.metadata,
    importedMissionSet: importedDraft.importedMissionSet,
    portalPool: importedDraft.portalPool,
    importSummary: importedDraft.importSummary,
    excludedPortalKeys: [],
    requiredPortalKeys: [],
    selectedStartPortalKey: importedDraft.selectedStartPortalKey,
    selectedEndPortalKey: null,
    routeOptions: importedDraft.routeOptions,
    currentGeneratedRoute: null,
    routeHistory: [],
  };
}

function buildDenseDistanceDraft() {
  const portalPool = [];
  const rows = 40;
  const columns = 30;
  const latitudeStart = 52.15;
  const longitudeStart = 6.85;
  let portalIndex = 0;

  for (let rowIndex = 0; rowIndex < rows; rowIndex += 1) {
    for (let columnIndex = 0; columnIndex < columns; columnIndex += 1) {
      portalPool.push({
        portalKey: `dense-portal-${portalIndex}`,
        guid: `dense-guid-${portalIndex}`,
        title: `Dense Portal ${portalIndex + 1}`,
        latitude:
          latitudeStart +
          rowIndex * 0.00055 +
          ((columnIndex + rowIndex) % 3) * 0.000012,
        longitude:
          longitudeStart +
          columnIndex * 0.0008 +
          ((rowIndex + portalIndex) % 3) * 0.000012,
        imageUrl: null,
        description: "",
        isImportedStartPoint: portalIndex === 0,
        sourceMissionIndex: Math.floor(portalIndex / 6),
        sourceStepIndex: portalIndex % 6,
        sourceMissionTitle: `Imported Dense Mission ${Math.floor(portalIndex / 6) + 1}`,
        sourceOrderIndex: portalIndex,
      });
      portalIndex += 1;
    }
  }

  return {
    id: "dense-draft-1",
    createdAt: 1,
    updatedAt: 1,
    source: {
      fileName: "dense-distance.umm.json",
    },
    metadata: {
      title: "Dense Distance Banner",
      description: "Dense import for long-distance reroute testing.",
      missionCount: 6,
      titleFormat: "Dense Distance Banner %02d",
    },
    importedMissionSet: {
      titleFormat: "T NN-M",
    },
    portalPool,
    importSummary: {
      importedMissionCount: 200,
      importedPortalCount: portalPool.length,
      uniquePortalCount: portalPool.length,
      activePortalCount: portalPool.length,
      duplicatePortalCount: 0,
      invalidPortalCount: 0,
      excludedPortalCount: 0,
    },
    excludedPortalKeys: [],
    requiredPortalKeys: [],
    selectedStartPortalKey: portalPool[0].portalKey,
    selectedEndPortalKey: null,
    routeOptions: {
      loopClosureMode: "prefer",
      minLoopDistanceMeters: 20000,
      maxLoopDistanceMeters: null,
    },
    currentGeneratedRoute: null,
    routeHistory: [],
  };
}

describe("routeGenerator", () => {
  test("generates a reroute with exact mission sizing and UMM export data", () => {
    const draft = buildTestDraft();
    const route = generateReroute(draft, { now: 12345 });
    const exportedMissionSet = buildUmmMissionSet(route, draft);
    const reparsedDraft = parseUmmMissionSet(
      JSON.stringify(exportedMissionSet),
      "rerouted-banner.umm.json"
    );

    expect(route.id).toBe("reroute-12345");
    expect(route.summary.portalCount).toBe(36);
    expect(route.missions).toHaveLength(6);
    expect(route.missions.every((mission) => mission.portals.length === 6)).toBe(
      true
    );
    expect(exportedMissionSet.missionSetName).toBe("Route Generator Banner");
    expect(exportedMissionSet.plannedBannerLength).toBe(6);
    expect(exportedMissionSet.fileFormatVersion).toBe(2);
    expect(exportedMissionSet.currentMission).toBe(0);
    expect(exportedMissionSet.titleFormat).toBe("T NN-M");
    expect(exportedMissionSet.missions).toHaveLength(6);
    expect(exportedMissionSet.missions[0].missionDescription).toBe(
      "Generated by a unit test."
    );
    expect(exportedMissionSet.missions[0].portals[0].isStartPoint).toBe(true);
    expect(exportedMissionSet.missions[0].portals[0].isOrnamented).toBe(false);
    expect(exportedMissionSet.missions[0].portals[0].type).toBe("PORTAL");
    expect(exportedMissionSet.missions[0].portals[0].objective).toEqual({
      type: "HACK_PORTAL",
      passphrase_params: {
        question: "",
        _single_passphrase: "",
      },
    });
    expect(reparsedDraft.metadata.missionCount).toBe(6);
    expect(reparsedDraft.portalPool).toHaveLength(36);
  });

  test("compacts stored routes and inflates them back into full route data", () => {
    const draft = buildTestDraft();
    const route = generateReroute(draft, { now: 12347 });
    const compactRoute = compactRouteSnapshot(route);
    const inflatedRoute = inflateStoredRoute(compactRoute, draft.portalPool);

    expect(compactRoute.orderedPortals).toBeUndefined();
    expect(compactRoute.missions).toBeUndefined();
    expect(compactRoute.portalOrder).toEqual(route.portalOrder);
    expect(inflatedRoute.portalOrder).toEqual(route.portalOrder);
    expect(inflatedRoute.missions).toHaveLength(route.missions.length);
    expect(inflatedRoute.orderedPortals[0].title).toBe(route.orderedPortals[0].title);
  });

  test("reports candidate progress while generating a reroute", () => {
    const draft = buildTestDraft();
    const progressSpy = vi.fn();

    generateReroute(draft, {
      now: 12346,
      onProgress: progressSpy,
      progressIntervalMs: 0,
    });

    expect(progressSpy).toHaveBeenCalled();

    const firstProgress = progressSpy.mock.calls[0][0];
    const finalProgress = progressSpy.mock.calls.at(-1)[0];

    expect(firstProgress.consideredCandidateCount).toBe(0);
    expect(firstProgress.totalCandidateCount).toBeGreaterThan(0);
    expect(finalProgress.consideredCandidateCount).toBe(
      finalProgress.totalCandidateCount
    );
    expect(finalProgress.progressRatio).toBe(1);
    expect(finalProgress.rejectedCandidateCount).toBeGreaterThanOrEqual(0);
  });

  test("keeps searching unique candidates beyond the initial budget before failing", () => {
    const draft = buildTestDraft();
    const progressSpy = vi.fn();
    const constrainedDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        minLoopDistanceMeters: 50000,
        maxLoopDistanceMeters: 60000,
      },
    };

    expect(() =>
      generateReroute(constrainedDraft, {
        now: 12346,
        onProgress: progressSpy,
        progressIntervalMs: 0,
        maxContinuousSearchBatches: 2,
      })
    ).toThrow(/hard minimum\/maximum distance constraints/i);

    const firstProgress = progressSpy.mock.calls[0][0];
    const finalProgress = progressSpy.mock.calls.at(-1)[0];

    expect(firstProgress.totalCandidateCount).toBeGreaterThan(0);
    expect(finalProgress.isContinuingUniqueSearch).toBe(true);
    expect(finalProgress.totalCandidateCount).toBeNull();
    expect(finalProgress.consideredCandidateCount).toBeGreaterThan(
      firstProgress.totalCandidateCount
    );
    expect(finalProgress.uniqueSearchBatchCount).toBeGreaterThan(0);
  });

  test("finds long reroutes from dense portal pools without continuous unique search", () => {
    const draft = buildDenseDistanceDraft();
    const progressSpy = vi.fn();
    const route = generateReroute(draft, {
      now: 22346,
      onProgress: progressSpy,
      progressIntervalMs: 0,
      maxContinuousSearchBatches: 0,
    });

    expect(route.summary.distanceMeters).toBeGreaterThanOrEqual(20000);

    const finalProgress = progressSpy.mock.calls.at(-1)[0];
    expect(finalProgress.isContinuingUniqueSearch).toBe(false);
  });

  test("restores the generated route and selected start portal from history snapshots", () => {
    const draft = buildTestDraft();
    const modifiedDraft = {
      ...draft,
      selectedStartPortalKey: draft.portalPool[8].portalKey,
      selectedEndPortalKey: draft.portalPool[30].portalKey,
      requiredPortalKeys: [draft.portalPool[10].portalKey],
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "prefer",
        minLoopDistanceMeters: 1000,
        maxLoopDistanceMeters: 20000,
      },
    };
    const route = generateReroute(modifiedDraft, { now: 45678 });
    const historyEntry = buildRouteHistoryEntry(route, modifiedDraft, {
      now: 45678,
    });
    const restoredDraft = restoreDraftFromHistoryEntry(draft, historyEntry, 56789);

    expect(restoredDraft.updatedAt).toBe(56789);
    expect(restoredDraft.selectedStartPortalKey).toBe(
      draft.portalPool[8].portalKey
    );
    expect(restoredDraft.selectedEndPortalKey).toBe(
      draft.portalPool[30].portalKey
    );
    expect(restoredDraft.excludedPortalKeys).toEqual([]);
    expect(restoredDraft.requiredPortalKeys).toEqual([
      draft.portalPool[10].portalKey,
    ]);
    expect(restoredDraft.routeOptions.loopClosureMode).toBe("prefer");
    expect(restoredDraft.routeOptions.minLoopDistanceMeters).toBe(1000);
    expect(restoredDraft.routeOptions.maxLoopDistanceMeters).toBe(20000);
    expect(restoredDraft.currentGeneratedRoute.id).toBe("reroute-45678");
    expect(restoredDraft.metadata.missionCount).toBe(6);
  });

  test("excludes disabled portals from generation and preserves them in history", () => {
    const draft = buildTestDraft();
    const modifiedDraft = {
      ...draft,
      excludedPortalKeys: [
        draft.portalPool[0].portalKey,
        draft.portalPool[1].portalKey,
      ],
      selectedStartPortalKey: draft.portalPool[2].portalKey,
    };
    const route = generateReroute(modifiedDraft, { now: 67890 });
    const historyEntry = buildRouteHistoryEntry(route, modifiedDraft, {
      now: 67890,
    });
    const restoredDraft = restoreDraftFromHistoryEntry(draft, historyEntry, 67901);

    expect(route.summary.activePortalCount).toBe(40);
    expect(route.summary.excludedPortalCount).toBe(2);
    expect(route.portalOrder).not.toContain(draft.portalPool[0].portalKey);
    expect(route.portalOrder).not.toContain(draft.portalPool[1].portalKey);
    expect(historyEntry.excludedPortalKeys).toEqual(modifiedDraft.excludedPortalKeys);
    expect(restoredDraft.excludedPortalKeys).toEqual(
      modifiedDraft.excludedPortalKeys
    );
    expect(restoredDraft.selectedStartPortalKey).toBe(
      draft.portalPool[2].portalKey
    );
  });

  test("uses an optional end portal as the final portal in the reroute", () => {
    const draft = buildTestDraft();
    const modifiedDraft = {
      ...draft,
      selectedStartPortalKey: draft.portalPool[4].portalKey,
      selectedEndPortalKey: draft.portalPool[34].portalKey,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "no-loop",
      },
    };
    const route = generateReroute(modifiedDraft, { now: 67895 });

    expect(route.portalOrder[0]).toBe(draft.portalPool[4].portalKey);
    expect(route.portalOrder.at(-1)).toBe(draft.portalPool[34].portalKey);
    expect(route.summary.startPortalKey).toBe(draft.portalPool[4].portalKey);
    expect(route.summary.endPortalKey).toBe(draft.portalPool[34].portalKey);
    expect(
      route.orderedPortals.every(
        (portal) => portal.sourceOrderIndex >= draft.portalPool[4].sourceOrderIndex
      )
    ).toBe(true);
    expect(
      route.orderedPortals
        .slice(0, 30)
        .map((portal) => portal.sourceOrderIndex)
    ).toEqual(
      Array.from({ length: 30 }, (_value, index) => index + 4)
    );
    expect(
      route.orderedPortals
        .slice(-6)
        .map((portal) => portal.sourceOrderIndex)
    ).toEqual([39, 38, 37, 36, 35, 34]);
    expect(
      route.missions[4].portals.map((portal) => portal.sourceOrderIndex)
    ).toEqual([28, 29, 30, 31, 32, 33]);
    expect(route.summary.maxHopMeters).toBeLessThan(2000);
  });

  test("uses custom distance limits, loop closure mode, and required portals", () => {
    const draft = buildTestDraft();
    const requiredPortalKeys = [
      draft.portalPool[9].portalKey,
      draft.portalPool[17].portalKey,
      draft.portalPool[25].portalKey,
    ];
    const modifiedDraft = {
      ...draft,
      requiredPortalKeys,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "no-loop",
        minLoopDistanceMeters: 1500,
        maxLoopDistanceMeters: 20000,
      },
    };
    const route = generateReroute(modifiedDraft, { now: 78901 });

    expect(route.summary.targetMinMeters).toBe(1500);
    expect(route.summary.targetMaxMeters).toBe(20000);
    expect(route.summary.loopClosureMode).toBe("no-loop");
    expect(route.summary.distanceMode).toBe("path");
    expect(route.summary.requiredPortalCount).toBe(3);
    requiredPortalKeys.forEach((portalKey) => {
      expect(route.portalOrder).toContain(portalKey);
    });
  });

  test("uses path distance for no-loop hard distance checks", () => {
    const draft = buildTestDraft();
    const noLoopDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "no-loop",
        maxLoopDistanceMeters: 6000,
      },
    };
    const route = generateReroute(noLoopDraft, { now: 78902 });

    expect(route.summary.loopClosureMode).toBe("no-loop");
    expect(route.summary.distanceMode).toBe("path");
    expect(route.summary.distanceMeters).toBe(route.summary.pathDistanceMeters);
    expect(route.summary.pathDistanceMeters).toBeLessThanOrEqual(6000);
    expect(route.summary.loopDistanceMeters).toBeGreaterThan(6000);
  });

  test("normalizes legacy allow-open drafts to no-loop mode", () => {
    const draft = buildTestDraft();
    const legacyDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "allow-open",
      },
    };
    const route = generateReroute(legacyDraft, { now: 78903 });

    expect(route.summary.loopClosureMode).toBe("no-loop");
    expect(route.summary.distanceMode).toBe("path");
  });

  test("enforces strict loop closure when requested", () => {
    const draft = buildTestDraft();
    const strictDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "strict",
      },
    };
    const route = generateReroute(strictDraft, { now: 79012 });

    expect(route.summary.loopClosureMode).toBe("strict");
    expect(route.summary.tailGapMeters).toBeLessThanOrEqual(180);
  });

  test("can satisfy strict loop closure with only a large hard maximum", () => {
    const draft = buildTestDraft();
    const strictDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        loopClosureMode: "strict",
        maxLoopDistanceMeters: 999999,
      },
    };
    const route = generateReroute(strictDraft, { now: 79013 });

    expect(route.summary.loopClosureMode).toBe("strict");
    expect(route.summary.loopDistanceMeters).toBeLessThanOrEqual(999999);
    expect(route.summary.tailGapMeters).toBeLessThanOrEqual(180);
  });

  test("rejects reroutes that cannot satisfy hard distance constraints", () => {
    const draft = buildTestDraft();
    const constrainedDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        minLoopDistanceMeters: 10,
        maxLoopDistanceMeters: 300,
      },
    };

    expect(() =>
      generateReroute(constrainedDraft, {
        now: 89012,
        maxContinuousSearchBatches: 2,
      })
    ).toThrow(/hard minimum\/maximum distance constraints/i);
  });

  test("logs rejected candidate reasons when rejection logging is enabled", () => {
    const consoleSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    const draft = buildTestDraft();
    const constrainedDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        minLoopDistanceMeters: 10,
        maxLoopDistanceMeters: 300,
      },
    };

    try {
      expect(() =>
        generateReroute(constrainedDraft, {
          now: 89014,
          logRejections: true,
          maxContinuousSearchBatches: 2,
        })
      ).toThrow(/hard minimum\/maximum distance constraints/i);

      expect(consoleSpy).toHaveBeenCalledWith(
        "[Banner Rerouter]",
        expect.stringMatching(/Rejected candidate route: .*hard maximum/i),
        expect.objectContaining({
          reasons: expect.arrayContaining([
            expect.stringMatching(/hard maximum/i),
          ]),
        })
      );
    } finally {
      consoleSpy.mockRestore();
    }
  });

  test("logs rejected candidate reasons when rerouter debug is enabled", () => {
    const originalUrl = window.location.href;
    const consoleSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    const draft = buildTestDraft();
    const constrainedDraft = {
      ...draft,
      routeOptions: {
        ...draft.routeOptions,
        minLoopDistanceMeters: 10,
        maxLoopDistanceMeters: 300,
      },
    };

    try {
      window.history.pushState({}, "", "/?openbanners-debug=1");

      expect(() =>
        generateReroute(constrainedDraft, {
          now: 89013,
          maxContinuousSearchBatches: 2,
        })
      ).toThrow(/hard minimum\/maximum distance constraints/i);

      expect(consoleSpy).toHaveBeenCalledWith(
        "[Banner Rerouter]",
        expect.stringMatching(/Rejected candidate route: .*hard maximum/i),
        expect.objectContaining({
          reasons: expect.arrayContaining([
            expect.stringMatching(/hard maximum/i),
          ]),
        })
      );
      expect(consoleSpy).toHaveBeenCalledWith(
        "[Banner Rerouter]",
        "Candidate rejection summary.",
        expect.objectContaining({
          totalRejectedCandidates: expect.any(Number),
          counts: expect.objectContaining({
            "above-hard-max-distance": expect.any(Number),
          }),
          finalRouteAccepted: false,
        })
      );
    } finally {
      window.history.pushState({}, "", originalUrl);
      consoleSpy.mockRestore();
    }
  });
});
